name: lstm_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow==2.13.0
      - yfinance
      - pandas
      - numpy
      - matplotlib
      - scikit-learn